<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WebPush" Version="1.0.13" />
    <PackageReference Include="FirebaseAdmin" Version="3.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../Core/CQRS/src/Aizen.Core.CQRS/Aizen.Core.CQRS.csproj" />
    <ProjectReference Include="../../../../Core/InfoAccessor/src/Aizen.Core.InfoAccessor.Abstraction/Aizen.Core.InfoAccessor.Abstraction.csproj" />
    <ProjectReference Include="../../../../Core/Cache/src/Aizen.Core.Cache.Abstraction/Aizen.Core.Cache.Abstraction.csproj" />
    <ProjectReference Include="../../../../Core/Messagebus/src/Aizen.Core.Messagebus.Abstraction/Aizen.Core.Messagebus.Abstraction.csproj" />
    <ProjectReference Include="../Aizen.Modules.Notification.Domain/Aizen.Modules.Notification.Domain.csproj" />
    <ProjectReference Include="../../../ServiceRequest/src/Aizen.Modules.ServiceRequest.Abstraction/Aizen.Modules.ServiceRequest.Abstraction.csproj" />
    <ProjectReference Include="../../../Messaging/src/Aizen.Modules.Messaging.Abstraction/Aizen.Modules.Messaging.Abstraction.csproj" />
  </ItemGroup>
</Project>
