using Aizen.Core.CQRS.Message;
using Aizen.Modules.Payment.Abstraction.Model.Result;

namespace Aizen.Modules.Payment.Application.Commands.IssueInvoice;

/// <summary>
/// Transitions a Draft invoice to Issued, assigning a formatted invoice number.
/// The number is generated by InvoiceNumberService (concurrency-safe, monthly sequence).
///
/// After Issue, the invoice is immutable. Corrections require a CreditNote (CRD) document.
/// </summary>
public sealed class IssueInvoiceCommand : AizenCommand<IssueInvoiceResult>
{
    public required long  InvoiceId       { get; init; }
    public          long? IssuedByUserId  { get; init; }
}
