<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Modules\Identity\src\Aizen.Modules.Identity.Abstraction\Aizen.Modules.Identity.Abstraction.csproj" />
    <ProjectReference Include="..\..\..\..\Core\Starter\src\Aizen.Core.Starter\Aizen.Core.Starter.csproj" />
    <ProjectReference Include="..\..\..\..\Core\UnitOfWork\src\Aizen.Core.UnitOfWork\Aizen.Core.UnitOfWork.csproj" />
    <ProjectReference Include="..\Aizen.Modules.Notification.Application\Aizen.Modules.Notification.Application.csproj" />
    <ProjectReference Include="..\Aizen.Modules.Notification.Repository\Aizen.Modules.Notification.Repository.csproj" />
    <ProjectReference Include="..\..\..\..\Modules\ServiceRequest\src\Aizen.Modules.ServiceRequest.Abstraction\Aizen.Modules.ServiceRequest.Abstraction.csproj" />
    <ProjectReference Include="..\..\..\..\Modules\Messaging\src\Aizen.Modules.Messaging.Abstraction\Aizen.Modules.Messaging.Abstraction.csproj" />
    <ProjectReference Include="..\..\..\..\Modules\CargoDry\src\Aizen.Modules.CargoDry.Abstraction\Aizen.Modules.CargoDry.Abstraction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
