namespace Aizen.Modules.Notification.Abstraction.Enum;

public enum NotificationType
{
    ServiceRequestCreated        = 100,
    ServiceRequestStatusChanged  = 101,
    OfferCreated                 = 110,
    OfferAccepted                = 111,
    OfferRejected                = 112,
    AssignmentCreated            = 120,
    AssignmentAccepted           = 121,
    AssignmentRejected           = 122,
    CompletionSubmitted          = 130,
    CompletionApproved           = 131,
    CompletionRejected           = 132,
    DisputeOpened                = 140,
    DisputeResolved              = 141,
    PaymentReleased              = 150,
    PaymentCaptured              = 151,
    PaymentCancelled             = 152,
    PaymentRefunded              = 153,
    PaymentReminderDue           = 154,
    PayoutCompleted              = 155,
    PaymentFailed                = 156,
    NewMessageReceived           = 200,
    MessageBlocked               = 201,
    CargoDryKitActivated         = 300,
    CargoDryKitExpiringReminder  = 301,
    CargoDryKitExpired           = 302,
    CargoDryKitRenewed           = 303,
    CargoDryKitRevoked                     = 304,
    /// <summary>Admin-triggered renewal notification dispatched through the Notification module. Phase 11.</summary>
    CargoDryRenewalNotificationRequested   = 305,
    ProfileApprovalDecision      = 400,
    PasswordRecoveryOtp          = 410,
    AdminBroadcast               = 900,
}
