<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Aizen.Modules.Identity.Domain\Aizen.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\Aizen.Modules.Identity.Core\Aizen.Modules.Identity.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Seed\Json\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>