---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAQDc5UtzJ6wKIerjoUdxtIwsMs4FPkfwAbja13JOt9z8B8ns1LBS6zH3UkwtV+6zkQA3XOovy2swEpqQnk6p7Yf/XI/cK7II7r1SX0RxufEFEE8siE4J7hlTHimt+eF2nXy+tk7+cbAZMENkanx6N514dY9zRjJiPvm2QohnguRNWBrxYO4HfYfzm5qjrclX69Nq0tvd3+LBCKpBgl3LK77dDCgNLJOm0woiZZetl7TuDyX5oAMwYyO9jluajkkrnMR3I46BYQhuWUrtskVddbtGGGp4YIAo5v0tXXE6AwkC0S+E9bx4rUPcq5AFqHOu2/0J/wK3DpwozOfJPmu6NHsFCUdvj/KiIdqxvBAQUr5T2DNFvoz/5VgBMFwr8+ics7QBRUItln4CAsaYnPLoUrkBAEl8H28oVS2HnkvqTkiM0rDRmstDdb57vla85VUY0JRqk0HLLEyn4JJRYCR1rremk7GNf33idrKkLqX5buTO9G5ppkYstyFw0vFrukFLAOVsUKE8iCUCuYHJwtr+UyzeaII5A2I1uPPgXH9QEo/An6cdq7tEpm5f1eFAoAK2RuXvyDf07gvaEBj0y1MoMStvDc2Sp6rjchxiINZZ06lFdKJcn4RthDzrbgCRTJAk8k+2WH6niYdC9dZXO7NvAoz3nkjnSVqrHv/fJAoYQfrYysaA5TNht2bLATMpjXzseeMd1FnqIhxhKzjj0n6uCHc2zNUzRvPK09mGWxbtjtXwTucdNNj32QpbzP72jdoMqL8wEMcXe3NB5qCv1qB6JqIq6MqacBO7a4R3s0AAYPkDyxtOLxyxZKp+wwkjTurjluaKxvhwSd49xyHhGGAmH2nb3UEsuikgoO9ZCAX81dejFe1wc9QVepn8+X9LLIopePS3W+df5z2+nyablisvXxb5XXgww125h4DttVQFDuUnKLqcLkXBHs
  template:
    metadata:
      name: cloudflared-tunnel
      namespace: cloudflared
