<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="9.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../Core/Cache/src/Aizen.Core.Cache/Aizen.Core.Cache.csproj" />
    <ProjectReference Include="../../../../Core/Starter/src/Aizen.Core.Starter/Aizen.Core.Starter.csproj" />
    <ProjectReference Include="../../../../Core/Starter/src/Aizen.Core.Starter.Bff/Aizen.Core.Starter.Bff.csproj" />
    <ProjectReference Include="../../../../Core/Api/src/Aizen.Core.Api/Aizen.Core.Api.csproj" />
    <ProjectReference Include="../../../../Core/Realtime/src/Aizen.Core.Realtime/Aizen.Core.Realtime.csproj" />
    <ProjectReference Include="../../../../Core/Realtime/src/Aizen.Core.Realtime.Abstraction/Aizen.Core.Realtime.Abstraction.csproj" />
    <ProjectReference Include="../Aizen.Bff.Marine.Participant.Mobile.Application/Aizen.Bff.Marine.Participant.Mobile.Application.csproj" />
    <ProjectReference Include="../../../../Modules/Notification/src/Aizen.Modules.Notification.Abstraction/Aizen.Modules.Notification.Abstraction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="configuration\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Aizen.Core.Common.Abstraction" />
    <Using Include="Aizen.Core.InfoAccessor.Abstraction" />
  </ItemGroup>

</Project>
