<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../Core/EFCore/src/Aizen.Core.EFCore/Aizen.Core.EFCore.csproj" />
    <ProjectReference Include="../../../../Core/Data/src/Aizen.Core.Data.Postgresql/Aizen.Core.Data.Postgresql.csproj" />
    <ProjectReference Include="../Aizen.Modules.Profile.Domain/Aizen.Modules.Profile.Domain.csproj" />
    <ProjectReference Include="../Aizen.Modules.Profile.Abstraction/Aizen.Modules.Profile.Abstraction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Aizen.Core.Common.Abstraction" />
  </ItemGroup>

</Project>
