<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

<ItemGroup>
    <ProjectReference Include="..\Aizen.Modules.Vessel.Domain\Aizen.Modules.Vessel.Domain.csproj" />
    <ProjectReference Include="..\Aizen.Modules.Vessel.Core\Aizen.Modules.Vessel.Core.csproj" />
    <ProjectReference Include="../../../FileStorage/src/Aizen.Modules.FileStorage.Abstraction/Aizen.Modules.FileStorage.Abstraction.csproj" />
    <ProjectReference Include="../../../../Core/RemoteCall/src/Aizen.Core.RemoteCall.Abstraction/Aizen.Core.RemoteCall.Abstraction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Seed\Json\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Aizen.Core.Common.Abstraction" />
  </ItemGroup>
</Project>
