// <auto-generated />
using System;
using Aizen.Modules.Profile.Repository.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aizen.Modules.Profile.Repository.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    partial class ProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profile")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aizen.Modules.Profile.Domain.Entities.Performance.ProfileDecisionLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateHost")
                        .HasColumnType("text");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifyHost")
                        .HasColumnType("text");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("NewScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<int?>("NewTier")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PreviousScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<int?>("PreviousTier")
                        .HasColumnType("integer");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProfileType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PublicId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_profile_decision_logs_EventType");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_profile_decision_logs_OccurredAtUtc");

                    b.HasIndex("ProfileId", "ProfileType")
                        .HasDatabaseName("IX_profile_decision_logs_ProfileId_ProfileType");

                    b.ToTable("profile_decision_logs", "profile");
                });

            modelBuilder.Entity("Aizen.Modules.Profile.Domain.Entities.Performance.ProfileMetricCacheEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CachedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateHost")
                        .HasColumnType("text");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MetricValueJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifyHost")
                        .HasColumnType("text");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProfileType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PublicId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_profile_metric_caches_ExpiresAtUtc");

                    b.HasIndex("ProfileId", "ProfileType", "MetricKey")
                        .IsUnique()
                        .HasDatabaseName("UIX_profile_metric_caches_ProfileId_ProfileType_MetricKey");

                    b.ToTable("profile_metric_caches", "profile");
                });

            modelBuilder.Entity("Aizen.Modules.Profile.Domain.Entities.Performance.ProfilePerformanceSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ActiveRiskSignalMaxSeverity")
                        .HasColumnType("integer");

                    b.Property<decimal>("CargoDryScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("ConfidenceLevel")
                        .HasColumnType("integer");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateHost")
                        .HasColumnType("text");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<decimal>("FinancialReliabilityScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("HasActiveRiskSignal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifyHost")
                        .HasColumnType("text");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OperationalDisciplineScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("PlatformComplianceScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("PriorityTier")
                        .HasColumnType("integer");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProfileType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PublicId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid");

                    b.Property<decimal>("RiskPenaltyScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceRequestScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime?>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HasActiveRiskSignal")
                        .HasDatabaseName("IX_profile_performance_snapshots_HasActiveRiskSignal");

                    b.HasIndex("PriorityTier")
                        .HasDatabaseName("IX_profile_performance_snapshots_PriorityTier");

                    b.HasIndex("ProfileId", "ProfileType")
                        .IsUnique()
                        .HasDatabaseName("UIX_profile_performance_snapshots_ProfileId_ProfileType");

                    b.ToTable("profile_performance_snapshots", "profile");
                });

            modelBuilder.Entity("Aizen.Modules.Profile.Domain.Entities.Performance.ProfileRiskSignalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateHost")
                        .HasColumnType("text");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifyHost")
                        .HasColumnType("text");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProfileType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PublicId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ResolvedByUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("SignalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("SourceEntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceModule")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_profile_risk_signals_Severity");

                    b.HasIndex("SignalCode")
                        .HasDatabaseName("IX_profile_risk_signals_SignalCode");

                    b.HasIndex("ProfileId", "ProfileType", "IsResolved")
                        .HasDatabaseName("IX_profile_risk_signals_ProfileId_ProfileType_IsResolved");

                    b.ToTable("profile_risk_signals", "profile");
                });

            modelBuilder.Entity("Aizen.Modules.Profile.Domain.Entities.Performance.ProfileScoreComponentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CalculatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateHost")
                        .HasColumnType("text");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MetricCount")
                        .HasColumnType("integer");

                    b.Property<string>("MetricsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifyHost")
                        .HasColumnType("text");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProfileType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PublicId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid");

                    b.Property<decimal>("RawScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal>("WeightedContribution")
                        .HasColumnType("numeric(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId")
                        .HasDatabaseName("IX_profile_score_components_SnapshotId");

                    b.HasIndex("ProfileId", "ProfileType")
                        .HasDatabaseName("IX_profile_score_components_ProfileId_ProfileType");

                    b.HasIndex("SnapshotId", "Category")
                        .IsUnique()
                        .HasDatabaseName("UIX_profile_score_components_SnapshotId_Category");

                    b.ToTable("profile_score_components", "profile");
                });

            modelBuilder.Entity("Aizen.Modules.Profile.Domain.Entities.Performance.ProfileScoreHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreateHost")
                        .HasColumnType("text");

                    b.Property<long?>("CreateUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModifyHost")
                        .HasColumnType("text");

                    b.Property<long?>("ModifyUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("PriorityTier")
                        .HasColumnType("integer");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProfileType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PublicId")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<string>("TriggerReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("PriorityTier")
                        .HasDatabaseName("IX_profile_score_history_PriorityTier");

                    b.HasIndex("RecordedAtUtc")
                        .HasDatabaseName("IX_profile_score_history_RecordedAtUtc");

                    b.HasIndex("ProfileId", "ProfileType")
                        .HasDatabaseName("IX_profile_score_history_ProfileId_ProfileType");

                    b.ToTable("profile_score_history", "profile");
                });
#pragma warning restore 612, 618
        }
    }
}
