using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Aizen.Modules.ReferenceData.Repository.Options;
using Aizen.Modules.ReferenceData.Repository.Seed.Models.Location;
using Aizen.Modules.ReferenceData.Repository.Seed.Readers;
using FluentAssertions;
using Microsoft.Extensions.Options;
using Xunit;

namespace Aizen.Modules.ReferenceData.Repository.UnitTests.Location;

/// <summary>
/// Validates the shipped full-ISO <c>Location/countries.json</c> (generated by <c>tools/countries-seed</c>) against the
/// seed model + the flag-picker's needs: many countries, the pinned yacht-flag states present, and every row carrying
/// the fields the picker + name resolver require (code + en fallback name).
/// </summary>
public sealed class CountriesSeedDataTests
{
    private static string SeedJsonRoot([CallerFilePath] string thisFile = "")
    {
        // <module>/tests/<UnitTests>/Location/CountriesSeedDataTests.cs → up 3 → <module> (Modules/ReferenceData)
        var moduleRoot = Directory.GetParent(thisFile)!.Parent!.Parent!.Parent!.FullName;
        return Path.Combine(moduleRoot, "src", "Aizen.Modules.ReferenceData.Repository", "Seed", "Json");
    }

    private static ReferenceDataJsonSeedReader Reader()
        => new(Microsoft.Extensions.Options.Options.Create(new ReferenceDataSeedOptions
        {
            JsonRootPath = SeedJsonRoot(),
            FailOnMissingRequiredFile = false,
        }));

    [Fact]
    public async Task Countries_Seed_Is_Full_And_Well_Formed()
    {
        var countries = await Reader().ReadListAsync<LocationCountrySeedModel>("Location/countries.json");

        countries.Count.Should().BeGreaterThan(190); // full ISO list, not just TR

        // Every row: a 2-letter code, an English fallback name (resolver depends on it), a numeric + phone code.
        countries.Should().OnlyContain(c =>
            !string.IsNullOrWhiteSpace(c.CountryCode) && c.CountryCode.Length == 2 &&
            c.Name != null && c.Name.ContainsKey("en") && !string.IsNullOrWhiteSpace(c.Name["en"]) &&
            !string.IsNullOrWhiteSpace(c.NumericCode) && !string.IsNullOrWhiteSpace(c.PhoneCode));

        // No duplicate codes (upsert key).
        countries.Select(c => c.CountryCode.ToUpperInvariant()).Distinct().Count()
            .Should().Be(countries.Count);

        // Pinned yacht-flag states resolve, each with a Turkish label for the picker.
        var pinned = new[] { "US", "MT", "MH", "IT", "GR", "GB", "FR", "NL", "PA", "KY" };
        foreach (var code in pinned)
        {
            var row = countries.SingleOrDefault(c => c.CountryCode == code);
            row.Should().NotBeNull($"pinned flag state {code} must be seeded");
            row!.Name.Should().ContainKey("tr");
        }
    }
}
