<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Messagebus\src\Aizen.Core.Messagebus\Aizen.Core.Messagebus.csproj"/>
    <ProjectReference Include="..\..\..\Cache\src\Aizen.Core.Cache\Aizen.Core.Cache.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="9.0.0"/>
  </ItemGroup>
</Project>