<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../Core/EFCore/src/Aizen.Core.EFCore/Aizen.Core.EFCore.csproj" />
    <ProjectReference Include="../../../../Core/Data/src/Aizen.Core.Data.Postgresql/Aizen.Core.Data.Postgresql.csproj" />
    <ProjectReference Include="../../../../Core/Data/src/Aizen.Core.Data.Mongo/Aizen.Core.Data.Mongo.csproj" />
    <ProjectReference Include="../Aizen.Modules.CargoDry.Domain/Aizen.Modules.CargoDry.Domain.csproj" />
    <ProjectReference Include="../Aizen.Modules.CargoDry.Abstraction/Aizen.Modules.CargoDry.Abstraction.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.27.0" />
  </ItemGroup>
</Project>
